### ISSUE TITLE
Old Lasair URL is burned into the code

### ISSUE THREAD

**Issue by genghisken** [lsst-uk/lasair_api#7]
Have been updating the Colab examples to add endpoint = "https://lasair-ztf.lsst.ac.uk" into the instantiation code.

This works fine, but for the Streams API example, when requesting more information on a stream...

```
L = lasair(token, endpoint = "https://lasair-ztf.lsst.ac.uk/api")

try:
    result = L.streams_topics(regex)
except LasairError as e:
    print(e)

for row in result:
    print(row['topic'], row['more_info'])
```

I get the following list...

```
lasair_2OrphanSearch https://lasair-iris.roe.ac.uk/query/1/
lasair_2SN-likecandidates https://lasair-iris.roe.ac.uk/query/2/
lasair_2AllnucleartransientsandTDEcandidates https://lasair-iris.roe.ac.uk/query/3/
lasair_2SherlockCVs https://lasair-iris.roe.ac.uk/query/4/
lasair_2RemoteCFroObject https://lasair-iris.roe.ac.uk/query/10/
lasair_2C-SNAILS https://lasair-iris.roe.ac.uk/query/15/
lasair_2Lightweight https://lasair-iris.roe.ac.uk/query/41/
lasair_51recentSNcandidateslargedm https://lasair-iris.roe.ac.uk/query/50/
lasair_51recentSNcandidateslargedmdtfainthost https://lasair-iris.roe.ac.uk/query/51/
lasair_51recentSNcandidateshostspec-z0separation1arcsecorderedphysicalseparation https://lasair-iris.roe.ac.uk/query/57/
.
.
. etc
```

So the code is ignoring my endpoint override when reporting the URLs, though it's correctly using the endpoint override to talk to the service!

**Comment by RoyWilliams** [comment]
URL of the webserver now comes from settings
https://github.com/lsst-uk/lasair4/blob/main/webserver/lasairapi/serializers.py#L113

And endpoint for client is fixed in pull request
https://github.com/lsst-uk/lasair_api/blob/develop/lasair/lasair.py#L27
